"""empty message

Revision ID: ebe9b399cddf
Revises: 1ef7c1125163
Create Date: 2018-12-08 15:32:53.226920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe9b399cddf'
down_revision = '1ef7c1125163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BD_coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sat_lat', sa.Float(), nullable=True),
    sa.Column('sat_long', sa.Float(), nullable=True),
    sa.Column('sat_height', sa.Float(), nullable=True),
    sa.Column('ant_lat', sa.Float(), nullable=True),
    sa.Column('ant_long', sa.Float(), nullable=True),
    sa.Column('ant_height', sa.Float(), nullable=True),
    sa.Column('teta', sa.Float(), nullable=True),
    sa.Column('fi_priv', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BD_coordinates_ant_height'), 'BD_coordinates', ['ant_height'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_ant_lat'), 'BD_coordinates', ['ant_lat'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_ant_long'), 'BD_coordinates', ['ant_long'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_fi_priv'), 'BD_coordinates', ['fi_priv'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_sat_height'), 'BD_coordinates', ['sat_height'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_sat_lat'), 'BD_coordinates', ['sat_lat'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_sat_long'), 'BD_coordinates', ['sat_long'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_teta'), 'BD_coordinates', ['teta'], unique=False)
    op.create_index(op.f('ix_BD_coordinates_timestamp'), 'BD_coordinates', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BD_coordinates_timestamp'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_teta'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_sat_long'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_sat_lat'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_sat_height'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_fi_priv'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_ant_long'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_ant_lat'), table_name='BD_coordinates')
    op.drop_index(op.f('ix_BD_coordinates_ant_height'), table_name='BD_coordinates')
    op.drop_table('BD_coordinates')
    # ### end Alembic commands ###
